### ISSUE TITLE
Error connecting to my Kodi instance

### ISSUE THREAD

**Issue by redglory** [haikuginger/kodipydent#1]
Hey,

Was trying to use this handler and I can't connect to my Kodi instance.

I get the following error:
`>>> import kodipydent
>>> from kodipydent import Kodi
>>> my_kodi = Kodi("192.168.1.77")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/kodipydent/KodiClient.py", line 53, in Kodi
    hive = Hive(get_rpc.API.get())
  File "/usr/local/lib/python2.7/site-packages/beekeeper/api.py", line 195, in execute
    _timeout=self.timeout
  File "/usr/local/lib/python2.7/site-packages/beekeeper/comms.py", line 99, in send
    raise ResponseException(self.action.format(), err)
beekeeper.comms.ResponseException: Error message: 401/Unauthorized`

I have set default Kodi ports and have enabled remote access.

I use a password to connect to my Kodi instance and I can't pass it as an argument to your handler. Could this be the problem?

Thanks

**Comment by haikuginger** [comment]
> I use a password to connect to my Kodi instance and I can't pass it as an argument to your handler. Could this be the problem?

That would certainly do it! It should be relatively straightforward to add; would you like to submit a pull request to add it? If not, I'll certainly add it for you; it just might take a few days.

If you want to add it, follow [the beekeeper documentation](https://beekeeper.readthedocs.io/en/latest/how_does_it_work.html#type) to add `username` and `password` variables of the `http_basic_auth` type to both [the base hive](https://github.com/haikuginger/kodipydent/blob/master/kodipydent/KodiClient.py#L9) so that we can make the initial connection, to [the hive construction logic](https://github.com/haikuginger/kodipydent/blob/master/kodipydent/rpctohive.py#L18) that generates the hive we actually talk to Kodi with, and you'll need to pass it to the constructors of both. Be sure to set the variables as optional so that users not using a password won't be harassed for one.

**Comment by haikuginger** [comment]
@redglory, I've fixed this with #2, and kodiypydent 0.2 with the fix has been uploaded to PyPI - can you confirm that this resolves your problem? I can reopen if not, but I'd likely need some additional information to figure out what's going on.

**Comment by redglory** [comment]
Works great!

Just a quick off-topic. I had version 0.1 and pip wouldn't update mine to 0.3.1

**Comment by haikuginger** [comment]
@redglory, do you have stack trace or something similar? Note that if you have a previous version of a library installed, doing `pip install kodipydent` won't upgrade automatically; you'd need to specify the newer version to install.

**Comment by redglory** [comment]
Thanks for the info :)
