### ISSUE TITLE
Facade for the library

### ISSUE THREAD

**Issue by ujos** [haikuginger/kodipydent#10]
First of all I'd like to thank you for you time to create this library. 

I'd like to share my experience of usage this library. 

My task was to create an app, which sends command to Kodi to play some URL. That was not easy to do. As a new comer to Kodi JSON RPC, I do not know commands and parameters to JSON RPC. I've spent quite a lot of time to figure out which namespace (Player or Playlists) and which command to send. Even more time I've spent to find what parameters to pass. `item` parameter had to be a dictionary with the `file` variable which contains URL.

I believe code (in general) is written one time to be used many times. Because of that some effort have to be made to make code easy to use.

As I can see interface of the library is generated from `hive.json`. I believe that was done, as probably it is easier to maintain it in the future. However it is very hard to use it

* In the editor when I press `Ctrl+Space` I do not see list of supported functions
* When I select function and press `Ctrl+Space`, there is no hint about parameters.

I believe for this nice library decorator would be very handy to cover some most frequent use cases to make API more user friendly.

**Comment by haikuginger** [comment]
Hi @ujos! Thanks for the suggestion!

This is a bit tricky. Every IDE is different, but most add features like the one you want by *parsing*, but not *executing*, library code and exposing the symbols the library contains.

In the case of `kodipydent`, features like this won't work, because the actual entire library namespace isn't available until program execution time—most of the symbols (that would normally be defined as methods or attributes on a class) don't exist in parseable code, and are added on once a remote Kodi instance is contacted.

The upstream library that kodipydent uses to do this, beekeeper, is deprecated for many reasons, this among them. It'd likely take a full rewrite of kodipydent to expose its symbols to IDEs, so it's not likely to happen. One of the reasons for writing kodipydent in the first place was because Kodi's JSON-RPC surface is really large and I thought an intermediate solution (somewhere in between crafting custom functions for each possible API call and building full JSON requests inline) might be helpful.

If, however, you want a quick reference (albeit not integrated with your IDE), one way to achieve that is to load a `Kodi` instance in the Python REPL and run `print()` on it—beekeeper will lay out the API structure, including all the namespaces, methods and named parameters for each.

In general, though, the namespaces and methods will be identical to the names described in [the Kodi wiki's documentation of the JSON-RPC surface](https://kodi.wiki/view/JSON-RPC_API/v8).

I know this is a somewhat long-winded comment, but I hope it's helpful.

**Comment by ujos** [comment]
@haikuginger Thank you for hint. Will try.
